### PR TITLE
Add Scrapingbee to web services

### PR DESCRIPTION
**Pull request by ksahin**

### CODE REVIEW

**Comment by lorien** [comment]
New items go to tail of the list, not on first position.

**Comment by ksahin** [comment]
I wasn't sure about that but I looked at the last few commits and saw that Dataflowkit and Proxycrawl were both added in the first position.

**Comment by ksahin** [comment]
Updated!

**Comment by lorien** [comment]
> I wasn't sure about that but I looked at the last few commits and saw that Dataflowkit and Proxycrawl were both added in the first position.

Yeah. Some times I forgot to check item positions. Maybe in next time it will be your lucky day :)

**Pull request merged**
