### PR TITLE
Update python.md

### PR DESCRIPTION
**Pull request by Proteusiq**
added seleniumbase, photon,  and frontera

### CODE REVIEW

**Comment by lorien** [comment]
I do not think photon is web scraping crawler.

**Comment by Proteusiq** [comment]
May I know your reasons for thinking it is not a web crawler? Looking at how to use https://github.com/s0md3v/Photon it appears to be a crawler.

**Comment by lorien** [comment]
I do not think it is not a crawler. I do think it is not a web crawler FRAMEWORK. You've put it into framework category.

**Comment by Proteusiq** [comment]
Which category should I move it to?

**Comment by lorien** [comment]
Category: web content extraction

**Pull request closed without merging**
