### PR TITLE
Add link for Chinese version

### PR DESCRIPTION
**Pull request by Germey**
Hi, I made a Chinese version based on your Repo, thanks for your really helpful repo! 

I just add a badge link of Chinese version, and I also add reverse badge link for your repo, could you please help merge this? Really appreciated!

### CODE REVIEW

**Comment by Germey** [comment]
Looks like: 
image

**Comment by lorien** [comment]
I will not do it.

**Comment by Germey** [comment]
Could you please give a reason?

**Comment by lorien** [comment]
I do not see why should I promote your project. You literally copied links which I and other people have been collecting for years and now you also want I start promoting copy of my project. That does not make any sense.

**Comment by Germey** [comment]
Thank you, got it! Really appreciated for your works for collecting so helpful links! I will keep putting the original link of this repo and will also help promote your repo. Really appreciated!

**Pull request closed without merging**
